from __future__ import annotations

import json
import re
from pathlib import Path

from .paths import CUSTOM_CONTENT_DIR, TOOL_DIR

VALID_KINDS = ("item", "npc", "boss", "arena", "texture")
_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9_-]*$")


def is_valid_slug(slug: str) -> bool:
    return bool(_SLUG_RE.fullmatch(slug))


def title_from_slug(slug: str) -> str:
    return " ".join(part.capitalize() for part in slug.replace("_", "-").split("-"))


def _quote(value: str) -> str:
    return json.dumps(value)


def _yaml(kind: str, slug: str, name: str, description: str, like: str | None) -> str:
    like_value = _quote(like) if like else "null"
    return f"""# Voidscape content pack.
# Generated by scripts/content.sh new.

schema: voidscape-content/v1
kind: {kind}
slug: {slug}
name: {_quote(name)}
description: {_quote(description)}
status: draft

gameplay:
  like: {like_value}
  notes: ""

art:
  style_brief: "../../../tools/voidscape-content/templates/voidscape-art-brief.md"
  source_dir: "art/source"
  working_dir: "art/working"
  final_dir: "art/final"
  selected_concept: null

integration:
  server_defs: []
  client_defs: []
  cache_files: []
  spawn_files: []
  drop_files: []
  client_version_bump_required: false

rollout:
  beta_package_required: false
  test_notes: []
"""


def _prompt(kind: str, name: str, description: str) -> str:
    if kind == "item":
        target = "a transparent inventory icon that reads clearly at 48x32"
    elif kind == "npc":
        target = "an RSC-style NPC concept and later a consistent sprite sheet"
    elif kind == "boss":
        target = "a boss concept, arena mood, and later a strict sprite sheet"
    elif kind == "arena":
        target = "an arena concept with readable RSC terrain/material ideas"
    else:
        target = "a tileable or reusable RSC-style texture asset"
    return f"""Use the Voidscape art brief.

Asset: {name}
Description: {description}
Target: {target}

Generate 4 distinct directions. Keep them separate. Avoid UI text unless it is
part of the world art. Prioritize silhouette, scale, and in-game readability.
"""


def scaffold_pack(
    kind: str,
    slug: str,
    *,
    name: str | None = None,
    description: str = "",
    like: str | None = None,
    force: bool = False,
) -> Path:
    if kind not in VALID_KINDS:
        raise ValueError(f"kind must be one of: {', '.join(VALID_KINDS)}")
    if not is_valid_slug(slug):
        raise ValueError("slug must use lowercase letters, numbers, hyphens, or underscores")

    display_name = name or title_from_slug(slug)
    root = CUSTOM_CONTENT_DIR / slug
    manifest_path = root / "content.yaml"
    if root.exists() and not force:
        raise FileExistsError(f"{root} already exists; pass --force to refresh missing files")

    for child in (
        root / "art" / "prompts",
        root / "art" / "source",
        root / "art" / "working",
        root / "art" / "final",
    ):
        child.mkdir(parents=True, exist_ok=True)

    if force or not manifest_path.exists():
        manifest_path.write_text(_yaml(kind, slug, display_name, description, like))

    notes = root / "notes.md"
    if force or not notes.exists():
        notes.write_text(f"# {display_name}\n\n## Decisions\n\n## Test Notes\n")

    prompt_path = root / "art" / "prompts" / f"{kind}-concept.txt"
    if force or not prompt_path.exists():
        prompt_path.write_text(_prompt(kind, display_name, description))

    # Keep a local pointer so pack folders remain understandable when copied.
    brief_link = root / "art" / "prompts" / "voidscape-art-brief.md"
    if force or not brief_link.exists():
        brief_link.write_text((TOOL_DIR / "templates" / "voidscape-art-brief.md").read_text())

    return root
