CREATE TABLE IF NOT EXISTS portal_commerce_checkout_intents (
    intent_id VARCHAR(64) NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    provider VARCHAR(16) NOT NULL DEFAULT 'tebex',
    package_id VARCHAR(64) NOT NULL,
    expected_currency CHAR(3) NOT NULL,
    expected_amount_minor BIGINT UNSIGNED NOT NULL,
    basket_id VARCHAR(128),
    status VARCHAR(24) NOT NULL DEFAULT 'created',
    last_error_code VARCHAR(64),
    created_at_ms BIGINT UNSIGNED NOT NULL,
    expires_at_ms BIGINT UNSIGNED NOT NULL,
    updated_at_ms BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (intent_id),
    UNIQUE KEY uq_portal_commerce_intents_basket (basket_id),
    KEY idx_portal_commerce_intents_account_status (account_id, status, created_at_ms),
    CONSTRAINT chk_portal_commerce_intent_provider CHECK (provider = 'tebex'),
    CONSTRAINT chk_portal_commerce_intent_status CHECK (status IN ('created', 'basket_created', 'completed', 'failed', 'expired'))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS portal_commerce_webhook_events (
    webhook_id VARCHAR(128) NOT NULL,
    provider VARCHAR(16) NOT NULL DEFAULT 'tebex',
    event_type VARCHAR(64) NOT NULL,
    payload_sha256 CHAR(64) NOT NULL,
    transaction_id VARCHAR(128),
    status VARCHAR(24) NOT NULL DEFAULT 'received',
    attempt_count INT UNSIGNED NOT NULL DEFAULT 1,
    last_error_code VARCHAR(64),
    created_at_ms BIGINT UNSIGNED NOT NULL,
    processed_at_ms BIGINT UNSIGNED,
    updated_at_ms BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (webhook_id),
    UNIQUE KEY uq_portal_commerce_events_payload (payload_sha256),
    KEY idx_portal_commerce_events_transaction (transaction_id, event_type, status),
    CONSTRAINT chk_portal_commerce_event_provider CHECK (provider = 'tebex'),
    CONSTRAINT chk_portal_commerce_event_status CHECK (status IN ('received', 'processed', 'failed', 'ignored'))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS portal_commerce_payments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    provider VARCHAR(16) NOT NULL DEFAULT 'tebex',
    transaction_id VARCHAR(128) NOT NULL,
    intent_id VARCHAR(64) NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    basket_id VARCHAR(128) NOT NULL,
    package_id VARCHAR(64) NOT NULL,
    quantity INT UNSIGNED NOT NULL,
    payment_sequence VARCHAR(16) NOT NULL,
    currency CHAR(3) NOT NULL,
    expected_amount_minor BIGINT UNSIGNED NOT NULL,
    product_paid_amount_minor BIGINT UNSIGNED NOT NULL,
    transaction_paid_amount_minor BIGINT UNSIGNED NOT NULL,
    tax_and_adjustments_minor BIGINT NOT NULL,
    status VARCHAR(24) NOT NULL,
    completed_at_ms BIGINT UNSIGNED NOT NULL,
    updated_at_ms BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_portal_commerce_payment_transaction (provider, transaction_id),
    UNIQUE KEY uq_portal_commerce_payment_intent (intent_id),
    KEY idx_portal_commerce_payments_account_status (account_id, status, completed_at_ms),
    CONSTRAINT fk_portal_commerce_payment_intent FOREIGN KEY (intent_id)
        REFERENCES portal_commerce_checkout_intents (intent_id),
    CONSTRAINT chk_portal_commerce_payment_provider CHECK (provider = 'tebex'),
    CONSTRAINT chk_portal_commerce_payment_quantity CHECK (quantity = 1),
    CONSTRAINT chk_portal_commerce_payment_sequence CHECK (payment_sequence = 'oneoff'),
    CONSTRAINT chk_portal_commerce_payment_status CHECK (status IN ('complete', 'refunded', 'disputed', 'dispute_lost', 'restored', 'review'))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS portal_commerce_entitlements (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    payment_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    provider VARCHAR(16) NOT NULL DEFAULT 'tebex',
    transaction_id VARCHAR(128) NOT NULL,
    line_key VARCHAR(128) NOT NULL,
    package_id VARCHAR(64) NOT NULL,
    unit_index INT UNSIGNED NOT NULL DEFAULT 1,
    state VARCHAR(24) NOT NULL DEFAULT 'pending',
    claimed_player_id BIGINT UNSIGNED,
    claimed_item_id BIGINT UNSIGNED,
    claimed_at_ms BIGINT UNSIGNED,
    review_reason VARCHAR(64),
    created_at_ms BIGINT UNSIGNED NOT NULL,
    updated_at_ms BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_portal_commerce_entitlement_line (provider, transaction_id, line_key, unit_index),
    KEY idx_portal_commerce_entitlements_account_state (account_id, state, created_at_ms),
    CONSTRAINT fk_portal_commerce_entitlement_payment FOREIGN KEY (payment_id)
        REFERENCES portal_commerce_payments (id),
    CONSTRAINT chk_portal_commerce_entitlement_provider CHECK (provider = 'tebex'),
    CONSTRAINT chk_portal_commerce_entitlement_unit CHECK (unit_index = 1),
    CONSTRAINT chk_portal_commerce_entitlement_state CHECK (state IN ('pending', 'claimed', 'revoked', 'frozen', 'review'))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
