const S={masters:[],current:null,token:"",tool:"paint",undo:[],redo:[],imported:null,importBase:null,showAnchors:false,showHeat:false,playing:null};
const C=document.querySelector('#canvas'),X=C.getContext('2d',{willReadFrequently:true}),P=document.querySelector('#preview'),PX=P.getContext('2d');X.imageSmoothingEnabled=false;PX.imageSmoothingEnabled=false;
const status=t=>document.querySelector('#status').textContent=t; const snapshot=()=>X.getImageData(0,0,C.width,C.height); const push=()=>{S.undo.push(snapshot());S.redo=[]};
async function load(name){S.current=name;const img=new Image();img.src=`/api/master/${name}.png?t=${Date.now()}`;await img.decode();C.width=img.width;C.height=img.height;X.clearRect(0,0,C.width,C.height);X.drawImage(img,0,0);drawPreview();status(name)}
function drawPreview(){P.width=C.width;P.height=C.height;PX.clearRect(0,0,P.width,P.height);PX.drawImage(C,0,0);if(S.showAnchors){PX.fillStyle='#ff00ff';PX.fillRect(P.width/2-1,7,3,5)}if(S.showHeat){PX.fillStyle='#ff000088';PX.fillRect(P.width/2-5,16,10,10)}}
fetch('/api/state').then(r=>r.json()).then(s=>{S.masters=s.masters;S.token=s.token;document.querySelector('#mode').textContent=s.readOnly?'Read-only legacy comparison':'Writable synthetic workspace';if(s.readOnly)document.body.classList.add('readonly');for(const n of s.masters){const b=document.createElement('button');b.className='master';b.textContent=n;b.onclick=()=>load(n);document.querySelector('#masters').append(b)}load(s.masters[0]);if(s.readOnly)document.querySelector('#save').disabled=true});
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>S.tool=b.dataset.tool);let drawing=false;C.onpointerdown=e=>{push();drawing=true;paint(e)};C.onpointermove=e=>drawing&&paint(e);C.onpointerup=()=>{drawing=false;drawPreview()};
function paint(e){const r=C.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)*C.width/r.width),y=Math.floor((e.clientY-r.top)*C.height/r.height),n=+document.querySelector('#brush').value;if(S.tool==='pick'){const p=X.getImageData(x,y,1,1).data;document.querySelector('#color').value='#'+[p[0],p[1],p[2]].map(v=>v.toString(16).padStart(2,'0')).join('');drawing=false;return}X.fillStyle=S.tool==='erase'?'#00000000':document.querySelector('#color').value;S.tool==='erase'?X.clearRect(x,y,n,n):X.fillRect(x,y,n,n)}
document.querySelector('#undo').onclick=()=>{if(S.undo.length){S.redo.push(snapshot());X.putImageData(S.undo.pop(),0,0);drawPreview()}};document.querySelector('#redo').onclick=()=>{if(S.redo.length){S.undo.push(snapshot());X.putImageData(S.redo.pop(),0,0);drawPreview()}};document.querySelector('#clear').onclick=()=>{push();X.clearRect(0,0,C.width,C.height);drawPreview()};
function shift(dx,dy){push();const a=snapshot();X.clearRect(0,0,C.width,C.height);X.putImageData(a,dx,dy);drawPreview()}[['left',-1,0],['right',1,0],['up',0,-1],['down',0,1]].forEach(([id,x,y])=>document.querySelector('#'+id).onclick=()=>shift(x,y));
document.querySelector('#mirror').onclick=()=>{push();const t=document.createElement('canvas');t.width=C.width;t.height=C.height;const q=t.getContext('2d');q.translate(C.width,0);q.scale(-1,1);q.drawImage(C,0,0);X.clearRect(0,0,C.width,C.height);X.drawImage(t,0,0);drawPreview()};
document.querySelector('#import').onchange=async e=>{const img=new Image();img.src=URL.createObjectURL(e.target.files[0]);await img.decode();S.importBase=X.getImageData(0,0,C.width,C.height);S.imported=img;push();X.drawImage(img,0,0);drawPreview()};function scale(f){if(!S.imported)return;push();const w=Math.max(1,Math.round(S.imported.width*f)),h=Math.max(1,Math.round(S.imported.height*f));X.drawImage(S.imported,0,0,w,h);drawPreview()}document.querySelector('#smaller').onclick=()=>scale(.5);document.querySelector('#larger').onclick=()=>scale(2);document.querySelector('#applyImport').onclick=()=>{if(!S.imported)return;S.imported=null;S.importBase=null;status('Import applied')};document.querySelector('#cancelImport').onclick=()=>{if(!S.importBase)return;X.putImageData(S.importBase,0,0);S.imported=null;S.importBase=null;drawPreview();status('Import cancelled')};
document.querySelector('#anchors').onclick=()=>{S.showAnchors=!S.showAnchors;drawPreview()};document.querySelector('#heat').onclick=()=>{S.showHeat=!S.showHeat;drawPreview()};document.querySelector('#actual').onclick=()=>P.style.width=P.style.width==='auto'?'240px':'auto';document.querySelector('#play').onclick=()=>{if(S.playing){clearInterval(S.playing);S.playing=null}else{let i=0;S.playing=setInterval(()=>load(S.masters[++i%S.masters.length]),500)}};
document.querySelector('#save').onclick=()=>C.toBlob(async b=>{const r=await fetch(`/api/master/${S.current}.png`,{method:'PUT',headers:{'X-Appearance-Token':S.token},body:b});status(r.ok?'Saved '+S.current:'Save failed: '+await r.text())},'image/png');
